# Generated by Django 2.2.7 on 2019-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191129_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstandlastname',
            field=models.CharField(default='Generic Name', max_length=50),
        ),
    ]
